# Generated by Django 4.2.28 on 2026-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_agency_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter — ₹4,999/yr'), ('professional', 'Professional — ₹9,999/yr'), ('enterprise', 'Enterprise — ₹19,999/yr')], default='professional', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='subscription_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
