# Generated by Django 4.2.28 on 2026-02-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_chatroom_message_paymentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('contact_sharing', 'Attempted contact sharing'), ('platform_redirect', 'Attempted platform redirect')], max_length=30)),
                ('flagged_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='marketplace.agency')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='marketplace.chatroom')),
            ],
        ),
    ]
