# Generated by Django 4.2.28 on 2026-02-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_agencywarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', '✅ Booking Confirmed'), ('preparing', '📋 Preparing Itinerary'), ('documents', '📄 Documents Ready'), ('departing', '🚀 Departing Soon'), ('on_trip', '🗺️ Currently On Trip'), ('returning', '🏠 Returning Home'), ('completed', '🎉 Trip Completed'), ('cancelled', '❌ Cancelled')], default='confirmed', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Message shown to user about current status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_status', to='marketplace.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', '✅ Booking Confirmed'), ('preparing', '📋 Preparing Itinerary'), ('documents', '📄 Documents Ready'), ('departing', '🚀 Departing Soon'), ('on_trip', '🗺️ Currently On Trip'), ('returning', '🏠 Returning Home'), ('completed', '🎉 Trip Completed'), ('cancelled', '❌ Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='marketplace.tripstatus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
