# Generated by Django 4.2.28 on 2026-03-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_tripstatus_tripupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agency_payout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.package'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='marketplace.package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.offer'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='marketplace.offer'),
        ),
    ]
