# Generated by Django 4.2.28 on 2026-03-21 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0010_packageimage_packagereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='avg_accommodation_rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='avg_guides_rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='avg_overall_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3),
        ),
        migrations.AddField(
            model_name='agency',
            name='avg_transport_rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='avg_value_rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='total_review_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('user', 'User'), ('agency', 'Agency'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tripstatus',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('payment', 'Payment Issue'), ('refund', 'Refund Request'), ('booking', 'Booking Problem'), ('agency', 'Agency Complaint'), ('technical', 'Technical Issue'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open — AI Handling'), ('escalated', 'Escalated to Team'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('is_escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='marketplace.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant'), ('agent', 'Support Agent'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('agency_cancelled', 'Agency Cancelled Trip'), ('traveller_cancel', 'Traveller Cancellation'), ('service_failure', 'Service Not Delivered'), ('double_charge', 'Double Charged'), ('fraud', 'Fraudulent Transaction'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField(help_text='Amount to refund in INR')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('processed', 'Processed — Refund Sent'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('razorpay_refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='marketplace.booking')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='marketplace.supportticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
