# Generated by Django 4.2.28 on 2026-04-24 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0011_agency_avg_accommodation_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off')], default='percentage', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value e.g. 10 for 10%', max_digits=5)),
                ('max_discount_cap', models.IntegerField(blank=True, help_text='Max discount in ₹ (e.g. cap 10% at ₹500)', null=True)),
                ('min_booking_amount', models.IntegerField(default=0, help_text='Minimum booking amount to apply coupon')),
                ('max_uses', models.IntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('used_count', models.IntegerField(default=0, editable=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=10)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_coupons', to='marketplace.agency')),
                ('created_by_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='marketplace.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(help_text='Total amount paid by traveller')),
                ('base_amount', models.IntegerField(help_text='Base before GST')),
                ('gst_amount', models.IntegerField(help_text='GST collected')),
                ('discount_amount', models.IntegerField(default=0, help_text='Coupon discount applied')),
                ('trivasta_commission', models.IntegerField(help_text='5% of original base — Trivasta earnings')),
                ('agency_payout_amount', models.IntegerField(help_text='Amount to transfer to agency')),
                ('razorpay_transfer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='marketplace.agency')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_record', to='marketplace.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencyBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current')], default='current', max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('razorpay_account_id', models.CharField(blank=True, help_text='Razorpay linked account ID', max_length=100, null=True)),
                ('razorpay_fund_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted — Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('kyc_rejection_reason', models.TextField(blank=True)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='marketplace.agency')),
                ('kyc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_applied', models.IntegerField(help_text='Actual discount amount in ₹')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='marketplace.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketplace.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
