# Generated by Django 4.2.28 on 2026-02-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': 'Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_type',
            field=models.CharField(choices=[('total', 'Total Budget'), ('per_person', 'Per Person')], default='total', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='num_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_mode',
            field=models.CharField(choices=[('any', '🚀 Any / Flexible'), ('flight', '✈️ Flight'), ('train', '🚂 Train'), ('bus', '🚌 Bus'), ('car', '🚗 Self Drive'), ('cruise', '🚢 Cruise')], default='any', max_length=20),
        ),
    ]
