# Generated by Django 4.2.28 on 2026-03-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_agency_avg_accommodation_rating_and_more'),
        ('trips', '0003_booking_review_reviewreply_reviewhelpfulvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='marketplace.booking'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
